<?php

namespace App\Controller\Admin;

use App\Entity\Commande;
use App\Form\CommandeFormType;
use App\MedicarSmartBundle\Service\OpenRouterClient;
use App\Repository\CommandeRepository;
use Dompdf\Dompdf;
use Dompdf\Options;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/commande', name: 'admin_commande_')]
class CommandeController extends AbstractController
{
    #[Route('/', name: 'index', methods: ['GET'])]
    public function index(Request $request, CommandeRepository $repo): Response
    {
        $page = max(1, $request->query->getInt('page', 1));
        $limit = 10;
        $status = $request->query->get('status');
        $productId = $request->query->getInt('product');

        $commandes = $repo->findAllPaginated($page, $limit, $status ?: null, $productId ?: null);
        $total = $repo->countAll($status ?: null, $productId ?: null);

        return $this->render('admin/commande/index.html.twig', [
            'commandes' => $commandes,
            'currentPage' => $page,
            'totalPages' => (int) ceil($total / $limit),
            'total' => $total,
            'currentStatus' => $status,
            'currentProduct' => $productId,
        ]);
    }

    #[Route('/ai-summary', name: 'ai_summary', methods: ['POST'])]
    public function aiSummary(CommandeRepository $repo, OpenRouterClient $openRouterClient): JsonResponse
    {
        try {
            $orders = $repo->findBy([], ['totalPrice' => 'DESC']);

            if (!$orders) {
                return $this->json([
                    'summary' => 'No orders found. Create orders first, then generate an AI summary for Finance and HR.',
                    'generatedBy' => 'AI (OpenRouter)',
                ]);
            }

            $normalized = array_map(static function (Commande $commande, int $index): array {
                return [
                    'rank' => $index + 1,
                    'orderNumber' => $commande->getCommandeNumber(),
                    'date' => $commande->getCommandeDate()?->format('Y-m-d'),
                    'product' => $commande->getProduct()?->getName(),
                    'quantity' => $commande->getQuantity(),
                    'totalPrice' => (float) $commande->getTotalPrice(),
                    'status' => $commande->getStatus(),
                    'specialNotes' => $commande->getNotes() ?: 'None',
                ];
            }, $orders, array_keys($orders));

            $summary = $openRouterClient->generateOrderSummaryForFinanceAndHR($normalized);

            return $this->json([
                'summary' => $summary,
                'generatedBy' => 'AI (OpenRouter)',
            ]);
        } catch (\Throwable $e) {
            return $this->json([
                'summary' => 'Unable to generate order summary right now: ' . $e->getMessage(),
                'generatedBy' => 'AI (OpenRouter)',
            ]);
        }
    }

        #[Route('/ai-summary/pdf', name: 'ai_summary_pdf', methods: ['POST'])]
        public function aiSummaryPdf(Request $request): Response
        {
                $summary = trim((string) $request->request->get('summary', ''));
                $generatedBy = trim((string) $request->request->get('generatedBy', 'Generated by AI (OpenRouter)'));

                if ($summary === '') {
                        return new Response('No summary content to export.', Response::HTTP_BAD_REQUEST);
                }

                $options = new Options();
                $options->set('isHtml5ParserEnabled', true);
                $options->set('isRemoteEnabled', false);

                $dompdf = new Dompdf($options);

                $escapedSummary = nl2br(htmlspecialchars($summary, ENT_QUOTES, 'UTF-8'));
                $escapedGeneratedBy = htmlspecialchars($generatedBy, ENT_QUOTES, 'UTF-8');
                $generatedAt = (new \DateTimeImmutable())->format('Y-m-d H:i:s');

                $html = <<<HTML
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>AI Order Summary</title>
    <style>
        body { font-family: DejaVu Sans, Arial, sans-serif; color: #1f2937; line-height: 1.55; font-size: 12px; }
        .header { border-bottom: 2px solid #1d4ed8; margin-bottom: 16px; padding-bottom: 10px; }
        .title { font-size: 20px; font-weight: 700; margin: 0 0 4px; color: #0f172a; }
        .meta { font-size: 11px; color: #4b5563; }
        .badge { display: inline-block; margin-top: 8px; background: #dbeafe; color: #1e40af; padding: 4px 10px; border-radius: 20px; font-size: 11px; }
        .content { margin-top: 14px; background: #f8fafc; border: 1px solid #e5e7eb; border-radius: 8px; padding: 14px; }
        .footer { margin-top: 16px; font-size: 10px; color: #6b7280; border-top: 1px solid #e5e7eb; padding-top: 8px; }
    </style>
</head>
<body>
    <div class="header">
        <h1 class="title">Order Summary Report (Finance & HR)</h1>
        <div class="meta">Generated at: {$generatedAt}</div>
        <div class="badge">{$escapedGeneratedBy}</div>
    </div>
    <div class="content">{$escapedSummary}</div>
    <div class="footer">This report was generated from the admin Commandes module.</div>
</body>
</html>
HTML;

                $dompdf->loadHtml($html);
                $dompdf->setPaper('A4', 'portrait');
                $dompdf->render();

                $pdfOutput = $dompdf->output();
                $fileName = 'ai-order-summary-' . (new \DateTimeImmutable())->format('Ymd-His') . '.pdf';

                return new Response($pdfOutput, Response::HTTP_OK, [
                        'Content-Type' => 'application/pdf',
                        'Content-Disposition' => 'attachment; filename="' . $fileName . '"',
                ]);
        }

    #[Route('/new', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $em): Response
    {
        $commande = new Commande();
        $form = $this->createForm(CommandeFormType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            // Auto-generate commande number
            $commande->setCommandeNumber('CMD-' . strtoupper(uniqid()));
            $commande->setCommandeDate(new \DateTime());
            $commande->calculateTotalPrice();

            $em->persist($commande);
            $em->flush();
            $this->addFlash('success', 'Commande created successfully.');
            return $this->redirectToRoute('admin_commande_index');
        }

        return $this->render('admin/commande/form.html.twig', [
            'form' => $form,
            'commande' => $commande,
            'is_edit' => false,
        ]);
    }

    #[Route('/{id}', name: 'show', methods: ['GET'], requirements: ['id' => '\d+'])]
    public function show(Commande $commande): Response
    {
        return $this->render('admin/commande/show.html.twig', [
            'commande' => $commande,
        ]);
    }

    #[Route('/{id}/edit', name: 'edit', methods: ['GET', 'POST'], requirements: ['id' => '\d+'])]
    public function edit(Request $request, Commande $commande, EntityManagerInterface $em): Response
    {
        $form = $this->createForm(CommandeFormType::class, $commande);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $commande->calculateTotalPrice();
            $em->flush();
            $this->addFlash('success', 'Commande updated successfully.');
            return $this->redirectToRoute('admin_commande_index');
        }

        return $this->render('admin/commande/form.html.twig', [
            'form' => $form,
            'commande' => $commande,
            'is_edit' => true,
        ]);
    }

    #[Route('/{id}/delete', name: 'delete', methods: ['POST'], requirements: ['id' => '\d+'])]
    public function delete(Request $request, Commande $commande, EntityManagerInterface $em): Response
    {
        if ($this->isCsrfTokenValid('delete' . $commande->getId(), $request->request->get('_token'))) {
            $em->remove($commande);
            $em->flush();
            $this->addFlash('success', 'Commande deleted successfully.');
        }

        return $this->redirectToRoute('admin_commande_index');
    }
}
