<?php

namespace ContainerEywMFPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_2NZbGxXService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.2NZbGxX' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'medecin' => ['privates', '.errored..service_locator.2NZbGxX.App\\Entity\\Medecin', NULL, 'Cannot autowire service ".service_locator.2NZbGxX": it needs an instance of "App\\Entity\\Medecin" but this type has been excluded in "config/services.yaml".'],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'medecin' => 'App\\Entity\\Medecin',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.2NZbGxX'])) {
            return $container->privates['.service_locator.2NZbGxX'];
        }

        return $container->privates['.service_locator.2NZbGxX'] = $instance;
    }
}
