<?php

namespace ContainerEywMFPy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6JQQFiYService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6JQQFiY' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Controller\\AdminSecurityController::login' => ['privates', '.service_locator.0MQaTBY', 'get_ServiceLocator_0MQaTBYService', true],
            'App\\Controller\\Admin\\MedecinController::index' => ['privates', '.service_locator.3BoFVFw', 'get_ServiceLocator_3BoFVFwService', true],
            'App\\Controller\\Admin\\MedecinController::verify' => ['privates', '.service_locator.2NZbGxX', 'get_ServiceLocator_2NZbGxXService', true],
            'App\\Controller\\Admin\\MedecinController::unverify' => ['privates', '.service_locator.2NZbGxX', 'get_ServiceLocator_2NZbGxXService', true],
            'App\\Controller\\Admin\\MedecinController::delete' => ['privates', '.service_locator.2NZbGxX', 'get_ServiceLocator_2NZbGxXService', true],
            'App\\Controller\\DashboardController::settings' => ['privates', '.service_locator.3BoFVFw', 'get_ServiceLocator_3BoFVFwService', true],
            'App\\Controller\\ExploreController::index' => ['privates', '.service_locator.3BoFVFw', 'get_ServiceLocator_3BoFVFwService', true],
            'App\\Controller\\ProfileController::edit' => ['privates', '.service_locator.24Qf0r0', 'get_ServiceLocator_24Qf0r0Service', true],
            'App\\Controller\\ProfileController::showPublicProfile' => ['privates', '.service_locator.3BoFVFw', 'get_ServiceLocator_3BoFVFwService', true],
            'App\\Controller\\RegistrationController::register' => ['privates', '.service_locator.3FWkHlB', 'get_ServiceLocator_3FWkHlBService', true],
            'App\\Controller\\RegistrationController::medecinRegister' => ['privates', '.service_locator.3FWkHlB', 'get_ServiceLocator_3FWkHlBService', true],
            'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.0MQaTBY', 'get_ServiceLocator_0MQaTBYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.1vYpZ1B', 'get_ServiceLocator_1vYpZ1BService', true],
            'App\\Controller\\AdminSecurityController:login' => ['privates', '.service_locator.0MQaTBY', 'get_ServiceLocator_0MQaTBYService', true],
            'App\\Controller\\Admin\\MedecinController:index' => ['privates', '.service_locator.3BoFVFw', 'get_ServiceLocator_3BoFVFwService', true],
            'App\\Controller\\Admin\\MedecinController:verify' => ['privates', '.service_locator.2NZbGxX', 'get_ServiceLocator_2NZbGxXService', true],
            'App\\Controller\\Admin\\MedecinController:unverify' => ['privates', '.service_locator.2NZbGxX', 'get_ServiceLocator_2NZbGxXService', true],
            'App\\Controller\\Admin\\MedecinController:delete' => ['privates', '.service_locator.2NZbGxX', 'get_ServiceLocator_2NZbGxXService', true],
            'App\\Controller\\DashboardController:settings' => ['privates', '.service_locator.3BoFVFw', 'get_ServiceLocator_3BoFVFwService', true],
            'App\\Controller\\ExploreController:index' => ['privates', '.service_locator.3BoFVFw', 'get_ServiceLocator_3BoFVFwService', true],
            'App\\Controller\\ProfileController:edit' => ['privates', '.service_locator.24Qf0r0', 'get_ServiceLocator_24Qf0r0Service', true],
            'App\\Controller\\ProfileController:showPublicProfile' => ['privates', '.service_locator.3BoFVFw', 'get_ServiceLocator_3BoFVFwService', true],
            'App\\Controller\\RegistrationController:register' => ['privates', '.service_locator.3FWkHlB', 'get_ServiceLocator_3FWkHlBService', true],
            'App\\Controller\\RegistrationController:medecinRegister' => ['privates', '.service_locator.3FWkHlB', 'get_ServiceLocator_3FWkHlBService', true],
            'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.0MQaTBY', 'get_ServiceLocator_0MQaTBYService', true],
        ], [
            'kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Controller\\AdminSecurityController::login' => '?',
            'App\\Controller\\Admin\\MedecinController::index' => '?',
            'App\\Controller\\Admin\\MedecinController::verify' => '?',
            'App\\Controller\\Admin\\MedecinController::unverify' => '?',
            'App\\Controller\\Admin\\MedecinController::delete' => '?',
            'App\\Controller\\DashboardController::settings' => '?',
            'App\\Controller\\ExploreController::index' => '?',
            'App\\Controller\\ProfileController::edit' => '?',
            'App\\Controller\\ProfileController::showPublicProfile' => '?',
            'App\\Controller\\RegistrationController::register' => '?',
            'App\\Controller\\RegistrationController::medecinRegister' => '?',
            'App\\Controller\\SecurityController::login' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:loadRoutes' => '?',
            'App\\Controller\\AdminSecurityController:login' => '?',
            'App\\Controller\\Admin\\MedecinController:index' => '?',
            'App\\Controller\\Admin\\MedecinController:verify' => '?',
            'App\\Controller\\Admin\\MedecinController:unverify' => '?',
            'App\\Controller\\Admin\\MedecinController:delete' => '?',
            'App\\Controller\\DashboardController:settings' => '?',
            'App\\Controller\\ExploreController:index' => '?',
            'App\\Controller\\ProfileController:edit' => '?',
            'App\\Controller\\ProfileController:showPublicProfile' => '?',
            'App\\Controller\\RegistrationController:register' => '?',
            'App\\Controller\\RegistrationController:medecinRegister' => '?',
            'App\\Controller\\SecurityController:login' => '?',
        ]);

        if (isset($container->privates['.service_locator.6JQQFiY'])) {
            return $container->privates['.service_locator.6JQQFiY'];
        }

        return $container->privates['.service_locator.6JQQFiY'] = $instance;
    }
}
