controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

medicar_smart_bundle:
    resource:
        path: ../src/MedicarSmartBundle/Controller/
        namespace: App\MedicarSmartBundle\Controller
    type: attribute
