parameters:
    stripe_public_key: '%env(STRIPE_PUBLIC_KEY)%'
    forum_summarizer.base_url: '%env(resolve:FORUM_SUMMARIZER_BASE_URL)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Controller/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: ['controller.service_arguments']

    App\MedicarSmartBundle\:
        resource: '../src/MedicarSmartBundle/'
        exclude:
            - '../src/MedicarSmartBundle/Resources/'
            - '../src/MedicarSmartBundle/MedicarSmartBundle.php'

    App\Service\AiSuggestionService:
        arguments:
            $openAiApiKey: '%env(OPENAI_API_KEY)%'

    App\Service\ForumSummaryClient:
        arguments:
            $baseUrl: '%forum_summarizer.base_url%'
            $openRouterApiKey: '%env(OPENROUTER_API_KEY)%'

    App\Service\GeminiClient:
        arguments:
            $geminiApiKey: '%env(GEMINI_API_KEY)%'

    App\Service\DalleClient:
        arguments:
            $openAiApiKey: '%env(OPENAI_API_KEY)%'

    App\Service\ImageGeneratorService:
        arguments:
            $dalleClient: '@App\Service\DalleClient'
