<?php

namespace ContainerQddW1XL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3FWkHlBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3FWkHlB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'userPasswordHasher' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'userPasswordHasher' => '?',
            'entityManager' => '?',
        ]);

        if (isset($container->privates['.service_locator.3FWkHlB'])) {
            return $container->privates['.service_locator.3FWkHlB'];
        }

        return $container->privates['.service_locator.3FWkHlB'] = $instance;
    }
}
