<?php

namespace ContainerQddW1XL;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMedecinService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.2NZbGxX.App\Entity\Medecin' shared service.
     *
     * @return \App\Entity\Medecin
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.2NZbGxX": it needs an instance of "App\\Entity\\Medecin" but this type has been excluded in "config/services.yaml".');
    }
}
