<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Partner extends \App\Entity\Partner implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'city' => [parent::class, 'city', null, 16],
        "\0".parent::class."\0".'country' => [parent::class, 'country', null, 16],
        "\0".parent::class."\0".'createdAt' => [parent::class, 'createdAt', null, 16],
        "\0".parent::class."\0".'email' => [parent::class, 'email', null, 16],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null, 16],
        "\0".parent::class."\0".'isActive' => [parent::class, 'isActive', null, 16],
        "\0".parent::class."\0".'name' => [parent::class, 'name', null, 16],
        "\0".parent::class."\0".'phone' => [parent::class, 'phone', null, 16],
        "\0".parent::class."\0".'postalCode' => [parent::class, 'postalCode', null, 16],
        "\0".parent::class."\0".'registrationNumber' => [parent::class, 'registrationNumber', null, 16],
        "\0".parent::class."\0".'street' => [parent::class, 'street', null, 16],
        "\0".parent::class."\0".'type' => [parent::class, 'type', null, 16],
        "\0".parent::class."\0".'updatedAt' => [parent::class, 'updatedAt', null, 16],
        "\0".parent::class."\0".'website' => [parent::class, 'website', null, 16],
        'city' => [parent::class, 'city', null, 16],
        'country' => [parent::class, 'country', null, 16],
        'createdAt' => [parent::class, 'createdAt', null, 16],
        'email' => [parent::class, 'email', null, 16],
        'id' => [parent::class, 'id', null, 16],
        'isActive' => [parent::class, 'isActive', null, 16],
        'name' => [parent::class, 'name', null, 16],
        'phone' => [parent::class, 'phone', null, 16],
        'postalCode' => [parent::class, 'postalCode', null, 16],
        'registrationNumber' => [parent::class, 'registrationNumber', null, 16],
        'street' => [parent::class, 'street', null, 16],
        'type' => [parent::class, 'type', null, 16],
        'updatedAt' => [parent::class, 'updatedAt', null, 16],
        'website' => [parent::class, 'website', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
