<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerEywMFPy\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerEywMFPy/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerEywMFPy.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerEywMFPy\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerEywMFPy\App_KernelDevDebugContainer([
    'container.build_hash' => 'EywMFPy',
    'container.build_id' => '8f113f66',
    'container.build_time' => 1771801535,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerEywMFPy');
