<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWxgKnBm\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWxgKnBm/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWxgKnBm.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWxgKnBm\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWxgKnBm\App_KernelDevDebugContainer([
    'container.build_hash' => 'WxgKnBm',
    'container.build_id' => 'b3dcc377',
    'container.build_time' => 1772783014,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWxgKnBm');
